# -*- coding: utf-8 -*-
"""week1_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hy1advdq-G3X1ZIB2h7zPcYoJKCs-qdG

**ML/DL FELLOWSHIP: WEEK 1 MINI PROJECT**

**Question 1: User Data Collector**

Concepts Used: Input handling, dictionaries, validation, formatted strings
"""

user_info = {}
# Geting  input from a user
user_info["full_name"] = input("Enter your full name: ")
user_info["user_age"] = input("Enter your age: ")
user_info["user_email"] = input("Enter your email: ")
user_info["fav_number"] = input("Enter your favorite number: ")
# Validating email format
if "@" in user_info["user_email"] and "." in user_info["user_email"]:
    print("\nUser Information:")
    print(f"Full Name: {user_info['full_name']}")
    print(f"Age: {user_info['user_age']}")
    print(f"Email: {user_info['user_email']}")
    print(f"Favorite Number: {user_info['fav_number']}")
else:
    print("Invalid email format. Please enter a valid email.")

"""**Question 2: Even or Odd?**

Concepts Used: Functions, conditionals

"""

def is_even(number):
    if number % 2 == 0:
        print("The number is even.")
    else:
        print("The number is odd.")
is_even(7)

"""**Question 3: Temperature Converter**

Concepts Used: Functions, conditionals, arithmetic operations


"""

def convert_temperature(value, unit):
    if unit == "C":
        converted = (value * 9/5) + 32
        print(f"{value}°C is {converted:.2f}°F")
    elif unit == "F":
        converted = (value - 32) * 5/9
        print(f"{value}°F is {converted:.2f}°C")
    else:
        print("Invalid unit! Use 'C' for Celsius or 'F' for Fahrenheit.")
convert_temperature(25, "C")
convert_temperature(77, "F")

"""**Question 4: Finding Min & Max**

Concepts Used: Lists, functions, input handling
"""

def finding_max_min(numbers_list):
    return max(numbers_list), min(numbers_list)
numbers = []
for i in range(5):
    number = float(input(f"Enter number {i+1}: "))
    numbers.append(number)
biggest, smallest = finding_max_min(numbers)
print(f"The max number is: {biggest}")
print(f"The min number is: {smallest}")

"""**Question 5: Student Data Manager**

Concepts Used: Lists, tuples, dictionaries, loops
"""

def student_data_manager():
    students_list = []
    for _ in range(3):
        name = input("Enter student name: ")
        age = input("Enter student age: ")
        grade = input("Enter student grade: ")
        students_list.append((name, age, grade))
    students_dict = dict((name, (age, grade)) for name, age, grade in students_list)
    print("\nStudent Data:")
    print(students_dict)
student_data_manager()

"""**Question 6: Inventory Management System**

Concepts Used: Dictionaries, functions, conditionals
"""

def update_inventory(inventory, item, quantity):
    if item in inventory:
        inventory[item] = max(0, inventory[item] + quantity)
    else:
        print(f"{item} is not in the inventory.")
    return inventory
inventory = {
    "apple": 10,
    "banana": 5,
    "orange": 8,
    "grape": 12,
    "mango": 6
}
for _ in range(3):
    item_name = input("Enter item name: ")
    item_quantity = int(input("Enter quantity to add/remove: "))
    inventory = update_inventory(inventory, item_name, item_quantity)
print("Updated Inventory:")
for item, quantity in inventory.items():
    print(f"{item}: {quantity}")